export const COLORS = {
  MEDIUM_ORCHID: 'var(--brand-medium-orchid)',
  DEEP_PURPLE: 'var(--brand-deep-purple)',
  DEEP_PURPLE_HOVER: 'var(--brand-deep-purple-hover)',
  CHINA_PINK: 'var(--brand-china-pink)',
  HAN_BLUE: 'var(--brand-han-blue)',
  SPACE_GRAY_FROM: 'var(--brand-space-gray-from)',
  SPACE_GRAY_TO: 'var(--brand-space-gray-to)',
  STORM_GRAY: 'var(--brand-storm-gray)',
  DARK_GRAY: 'var(--brand-dark-gray)',

  BACKGROUND: 'var(--background)',
  BACKGROUND_CONTRAST: 'var(--background-contrast)',
  BACKGROUND_PROGRESS: 'var(--background-progress)',

  FOREGROUND: 'var(--foreground)',
  FOREGROUND_DARK: 'var(--foreground-dark)',
  FOREGROUND_CONTRAST: 'var(--foreground-contrast)',
  FOREGROUND_PROGRESS: 'var(--foreground-progress)',
  FOREGROUND_SUBTLE: 'var(--foreground-subtle)',
  FOREGROUND_DISABLED: 'var(--foreground-disabled)',
  DISABLED: 'var(--disabled)',

  BORDER_LIGHT: 'var(--border-light)',
  BORDER_DARK: 'var(--border-dark)',
  BORDER_PROGRESS: 'var(--border-progress)',
  BORDER_DISABLED: 'var(--border-disabled)',
  BORDER_FOCUS: 'var(--border-focus)',

  BACKGROUND_ERROR: 'var(--background-error)',
  FOREGROUND_ERROR: 'var(--foreground-error)',
  BORDER_ERROR: 'var(--border-error)',

  BACKGROUND_WARNING: 'var(--background-warning)',
  FOREGROUND_WARNING: 'var(--foreground-warning)',
  BORDER_WARNING: 'var(--border-warning)',

  BACKGROUND_SUCCESS: 'var(--background-success)',
  FOREGROUND_SUCCESS: 'var(--foreground-success)',
  BORDER_SUCCESS: 'var(--border-success)',

  CATEGORICAL_1: 'var(--categorical-1)',
  CATEGORICAL_2: 'var(--categorical-2)',
  CATEGORICAL_3: 'var(--categorical-3)',
  CATEGORICAL_4: 'var(--categorical-4)',
  CATEGORICAL_5: 'var(--categorical-5)',
  CATEGORICAL_6: 'var(--categorical-6)',
  CATEGORICAL_7: 'var(--categorical-7)',
  CATEGORICAL_8: 'var(--categorical-8)',
  CATEGORICAL_9: 'var(--categorical-9)',
  CATEGORICAL_10: 'var(--categorical-10)',
  CATEGORICAL_11: 'var(--categorical-11)',
  CATEGORICAL_12: 'var(--categorical-12)',
  CATEGORICAL_13: 'var(--categorical-13)',
  CATEGORICAL_14: 'var(--categorical-14)',
  CATEGORICAL_15: 'var(--categorical-15)',
};
